### ISSUE TITLE
Add ability to pass javavm init options 

### ISSUE THREAD

**Issue by uvlad7** [arton/rjb#109]
[Here](https://github.com/oxidize-rb/oxi-test/pull/11/files#diff-41d22aab9571958585b961aec06d19eb39d9916556d4f0a3657bb5740c73a614R177) is what I need to pass in Rust, to do the same in rjb, I need to set
```ruby
ENV['JAVA_TOOL_OPTIONS'] = '--add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED'
```
(or `_JAVA_OPTIONS`, or `JDK_JAVA_OPTIONS`)
It works, but generates an unsuppressable warning
```
Picked up JAVA_TOOL_OPTIONS: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED
```

I think it'd be nice to be able to set [JavaVMInitArgs](https://cr.openjdk.org/~zhouyx/cvmi/interface_doc/struct_java_v_m_init_args.html) fields, like array of arrays or hash of `options` and boolean ignoreUnrecognized.

**Comment by arton** [comment]
@uvlad7 I think you may set the second arguments of Rjb::load. It is for JVM options.
therefore you may call Rjb::load at first as
```
Rjb::load('.', ['--add-opens=java.base/sun.nio.ch=ALL-UNNAMED', '--add-opens=java.base/java.io=ALL-UNNAMED'])
```

or

```
Rjb::load(nil, ['--add-opens=java.base/sun.nio.ch=ALL-UNNAMED', '--add-opens=java.base/java.io=ALL-UNNAMED'])
```


- the first argument was default load path for jars, and '.' was the default value. it should set the first argument because jvm options is the positional argument.
