### ISSUE TITLE
How to specify signature?

### ISSUE THREAD

**Issue by uvlad7** [arton/rjb#110]
I need to [call](https://github.com/oxidize-rb/oxi-test/pull/11/files#diff-41d22aab9571958585b961aec06d19eb39d9916556d4f0a3657bb5740c73a614R214) `initialize(Ljava/util/List;)Lorg/jruby/Ruby;` static method, how can I specify that `Ljava/util/List;` part? Does it work the same for instance methods?

(It actually works like that
```ruby
JavaEmbedUtils._invoke('initialize', nil, ArrayList.new)
```
I'm just curious.)

**Comment by arton** [comment]
@uvlad7 I think you don't need to call with signature parameter.
I believe you can call the method as
```
JavaEmbedUtils.initialize(ArrayList.new())
```

Because Rjb checks the method signature with given parameters.
You should use _invoke when you call such as Foo#bar(short x) or Foo#bar(long x) because Rjb and Ruby can't judge given number was short or long.
