### ISSUE TITLE
Rjb vs. JRuby benchmarks

### ISSUE THREAD

**Issue by arbox** [arton/rjb#49]
It is merely a question not an issue. I think It would be useful to compare the performance of Rjb bindings on some commonly used Java library. Are there any ready benchmarks I'm not aware of? Should we compare the performance of Rjb vs. JRuby based bindings?

**Comment by arton** [comment]
Honestly I am not interest in comparing JRuby / Rjb. Because I know that MRB  invoking start from shell/cmd.exe is faster than JRuby for scripting. -- my common use case of ruby is just one shot scripting to convert text file or communicating remote box etc. Also my Rjb use case is just testing Java class that was developed by myself.
Therefore, if you think it's better to have such benchmarks that you mentioned, the ball is in your hand.

**Comment by arbox** [comment]
Ok, I see your point! No, that is not a vital task for now, I was wondering how to compare the performance of such complex setups. Will be done some day in the future.
