### ISSUE TITLE
Constant DL and Fiddle undefined

### ISSUE THREAD

**Issue by pacmanan** [arton/rjb#69]
Im using rjb to load a jar that I would use in my ruby script but each time I run my script i get an error message "Constants DL and Fiddle not defined". So far ive done the following things to try to get it to work.

1. Make sure jaVA_HOME is set before the script starts.
2. Tried using an older version of rjb.
3. Tried to require the gem 'Fiddle'.

Would like to mention that this same script works perfectly fine on a linux machine.

My setup is:

ruby 2.5.5 
JDK 11.0.3
Windows server 2012 R2 64bit

**Comment by arton** [comment]
Hi pacmana
Thank you for your report.

Rjb requires Fiddle (for ruby 2.0 or high) or DL(ruby 1.9 or low) to load JVM in the process.
And my acknowledgement tells me that ruby already has Fiddle or DL by the standard installation process.
If your installed ruby does not have Fiddle (because of the version is 2.5.5), you should install Fiddle for using Rjb.

Regards

**Comment by pacmanan** [comment]
If I include the Fiddle gem in my gem file, i then get an error stating "already initialized constant Fiddle" .

**Comment by arton** [comment]
I don't understand why you need gem. As my first comment, ruby standard install process prepared fiddle for you. That's because ruby make fiddle twice (the second one emits error as you wrote).
How did you prepare ruby ? Maybe your installation is corrupted at least about fiddle.so.
I believe that "cd win32;nmake;nmake install" is preferable way to install it.

**Comment by pacmanan** [comment]
"If your installed ruby does not have Fiddle (because of the version is 2.5.5), you should install Fiddle for using Rjb."

^I included the gem to test if it was installing Fiddle as part of ruby installation, which seems like it is and hence giving the error that the constant is already defined.

I'll try installing ruby using the above command and see is thats the issue. thanks

**Comment by pacmanan** [comment]
i installed ruby following the guide on the rubyinstaller.org site

**Comment by albandum** [comment]
Hi, getting the same issue, and running gem install fiddle doesn't change. 
Is RJB not compatible with ruby versions above 2.5 ?

**Comment by arton** [comment]
can't reproduce.
